src/main/urls.py
from django.contrib import admin
from django.urls import path, include

from url_shortener import urls
from url_shortener.views import home, shortened_url_detail, redirect_from_alias

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shortened_urls/', include('url_shortener.urls')),
    path('', home),
    path('<slug:alias>/detail/', shortened_url_detail),
    path('<slug:alias>/', redirect_from_alias),
]

src/url_shortener/urls.py
from django.urls import path

from url_shortener.views import UrlShortenerApi

app_name = 'url_shortener'
urlpatterns = [
    path('', UrlShortenerApi.as_view(), name='create'),
    path('<slug:alias>/', UrlShortenerApi.as_view()),
]

src/url_shortener/models.py
import random
import string
from django.db import models
from django.forms import ModelForm


class ShortenedUrlAliasField(models.SlugField):
    def pre_save(self, model_instance, add):
        if add:
            model_instance.alias = self.get_shortened_url_alias_slug()

        return model_instance.alias

    def get_shortened_url_alias_slug(self):
        alias = ''.join(random.choices(string.ascii_letters + string.digits + '_' + '-', k=6))

        if Shortened_Url.objects.filter(alias=alias).exists():
            return self.get_shortened_url_alias_slug()

        return alias

class Shortened_Url(models.Model):
    alias = ShortenedUrlAliasField(max_length=8, unique=True)
    origin_url = models.URLField(max_length=2048)


class ShortenedUrlForm(ModelForm):
    class Meta:
        model = Shortened_Url
        fields = ['origin_url']

src/url_shortener/views.py
import json
from http import HTTPStatus
from django.views import View
from django.shortcuts import render
from django.http import JsonResponse, HttpResponseRedirect
from url_shortener.models import Shortened_Url, ShortenedUrlForm


def home(request):
    return render(request, 'home.html')


def shortened_url_detail(request, alias):
    shortened_url = Shortened_Url.objects.get(alias=alias)

    return render(
        request,
        'shortened_url_detail.html',
        {'alias': alias, 'origin_url': shortened_url.origin_url}
    )


def redirect_from_alias(request, alias):
    shortened_url = Shortened_Url.objects.get(alias=alias)

    return HttpResponseRedirect(shortened_url.origin_url)


class UrlShortenerApi(View):
    def post(self, request):
        shortened_url_form = ShortenedUrlForm({
            'origin_url':json.loads(request.body).get('origin_url')
        })

        if not shortened_url_form.is_valid():
            return JsonResponse(shortened_url_form.errors)

        shortened_url = shortened_url_form.save()

        return JsonResponse({
            'alias': shortened_url.alias,
            'origin_url': shortened_url.origin_url
        }, status=HTTPStatus.CREATED)

    def get(self, request, alias):
        shortened_url = Shortened_Url.objects.get(alias=alias)

        return JsonResponse({
            'alias': shortened_url.alias,
            'origin_url': shortened_url.origin_url
        }, status=HTTPStatus.OK)

src/url_shortener/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>URL Shortener</title>
  <meta name="description" content="Awesome URL Shortener">
</head>

<body>
  <h1>URL Shortener</h1>
  <form action="{% url 'url_shortener:create' %}" method="post">
      <input type="text" name="origin_url" id="origin_url" placeholder="URL to short" />
    <input type="button" onclick="generateUrl()" value="Generate short URL!">
    </form>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script>
      function generateUrl() {
        axios({
          method: 'post',
          url: '/shortened_urls/',
          headers: {
            'X-CSRFToken': "{{ csrf_token }}"
          },
          data: {
            origin_url: document.getElementById("origin_url").value
          },
        }).then(response => {
          if (response.data.alias) {
            window.location.href = '/' + response.data.alias + '/detail/';
          } else {
            if (response.data.origin_url && Array.isArray(response.data.origin_url )) {
              for (let i=0;i<response.data.origin_url.length;i++) {
                alert(response.data.origin_url[i]);
              }
            }
          }
        }).catch(error => {
          alert(error);
        });
      }
    </script>
</body>
</html>

src/url_shortener/templates/shortened_url_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">

  <title>URL Shortener</title>
  <meta name="description" content="Awesome URL Shortener">
</head>

<body>
  <p>Origin URL: {{ origin_url }}</p>
  <p>Alias: {{ alias }}</p>
  <p>Link: <a href="http://{{ request.get_host }}/{{ alias }}">https://{{ request.get_host }}/{{ alias }}</a></p>
  <button type="button" onclick="window.location.href='/'">Generate Another URL</button>
</body>
</html>